
project_id = "nwxxrlvjfctjgwsjlvyv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions.send-task-reminders]
verify_jwt = false
