// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwxxrlvjfctjgwsjlvyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eHhybHZqZmN0amd3c2psdnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTQ0NDEsImV4cCI6MjA2MzM3MDQ0MX0.0M2rqMnj6Dekp1G0kIVk22u0KpES5yFfwf4JX7yyeJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);